// Code generated by goctl. DO NOT EDIT.
package types

type CloseRoomReq struct {
	Username string `json:"username"`
	RoomId   int64  `json:"roomId"`
}

type CloseRoomResp struct {
	Status int64 `json:"status"`
}

type CreatRoomReq struct {
	Username string `json:"username"`
	RoomName string `json:"roomName"`
}

type CreatRoomResp struct {
	RoomId int64 `json:"roomId"`
	Status int64 `json:"status"`
}

type GetRoomListReq struct {
	Page int64 `json:"page"`
}

type GetRoomListResp struct {
	Status   int64  `json:"status"`
	RoomList []Room `json:"roomList"`
}

type GetRoomPushAddressReq struct {
	Username string `json:"username"`
}

type GetRoomPushAddressResp struct {
	Status      int64  `json:"status"`
	PushAddress string `json:"pushAddress"`
	ChannelKey  string `json:"channelKey"`
	RoomId      int64  `json:"roomId"`
	RoomName    string `json:"roomName"`
}

type GetViewNumReq struct {
	RoomId int64 `json:"roomId"`
}

type GetViewNumResp struct {
	Status    int64 `json:"status"`
	ViewerNum int64 `json:"viewerNum"`
}

type JoinRoomReq struct {
	Username string `json:"username"`
	RoomId   int64  `json:"roomId"`
}

type JoinRoomResp struct {
	Status int64 `json:"status"`
}

type Room struct {
	RoomId    int64  `json:"roomId"`
	RoomName  string `json:"roomName"`
	RoomOwner string `json:"roomOwner"`
	ViewerNum int64  `json:"viewerNum"`
}
