// Code generated by goctl. DO NOT EDIT.
package types

type CreatRoomReq struct {
	RoomId int64 `json:"roomId"`
}

type CreatRoomResp struct {
	Status int64 `json:"status"`
}

type SendGiftReq struct {
	RoomId   int64  `json:"roomId"`
	Name     string `json:"name"`
	GiftType string `json:"giftType"`
}

type SendGiftResp struct {
	Status int64 `json:"status"`
}
