// Code generated by goctl. DO NOT EDIT.
package types

type ChargeReq struct {
	UserName int64 `json:"username"`
	Num      int64 `json:"num"`
}

type ChargeResp struct {
	Status int64 `json:"status"`
}

type GetUserInfoReq struct {
	Username int64 `json:"username"`
}

type GetUserInfoResp struct {
	Status   int64  `json:"status"`
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Money    int64  `json:"money"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Status       int64  `json:"status"`
	Token        string `json:"token"`
	ExpireTime   int64  `json:"expireTime"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Code     string `json:"code"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Status int64 `json:"status"`
}

type SendMessageReq struct {
	Mobile string `json:"mobile"`
}

type SendMessageResp struct {
	Status int64 `json:"status"`
}
