// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Status       int64  `json:"status"`
	Token        string `json:"token"`
	ExpireTime   int64  `json:"expire_time"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Code     string `json:"code"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Status int64 `json:"status"`
}

type SendMessageReq struct {
	Mobile string `json:"mobile"`
}

type SendMessageResp struct {
	Status int64 `json:"status"`
}
