// Code generated by goctl. DO NOT EDIT.
// Source: talk.proto

package talkroomservice

import (
	"context"

	"mygo/app/talkCenter/talk-rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatRoomReq    = pb.CreatRoomReq
	CreatRoomResp   = pb.CreatRoomResp
	JoinRaffleReq   = pb.JoinRaffleReq
	JoinRaffleResp  = pb.JoinRaffleResp
	SendGiftReq     = pb.SendGiftReq
	SendGiftResp    = pb.SendGiftResp
	StartRaffleReq  = pb.StartRaffleReq
	StartRaffleResp = pb.StartRaffleResp

	TalkRoomService interface {
		CreatRoom(ctx context.Context, in *CreatRoomReq, opts ...grpc.CallOption) (*CreatRoomResp, error)
		SendGift(ctx context.Context, in *SendGiftReq, opts ...grpc.CallOption) (*SendGiftResp, error)
		StartRaffle(ctx context.Context, in *StartRaffleReq, opts ...grpc.CallOption) (*StartRaffleResp, error)
		JoinRaffle(ctx context.Context, in *JoinRaffleReq, opts ...grpc.CallOption) (*JoinRaffleResp, error)
	}

	defaultTalkRoomService struct {
		cli zrpc.Client
	}
)

func NewTalkRoomService(cli zrpc.Client) TalkRoomService {
	return &defaultTalkRoomService{
		cli: cli,
	}
}

func (m *defaultTalkRoomService) CreatRoom(ctx context.Context, in *CreatRoomReq, opts ...grpc.CallOption) (*CreatRoomResp, error) {
	client := pb.NewTalkRoomServiceClient(m.cli.Conn())
	return client.CreatRoom(ctx, in, opts...)
}

func (m *defaultTalkRoomService) SendGift(ctx context.Context, in *SendGiftReq, opts ...grpc.CallOption) (*SendGiftResp, error) {
	client := pb.NewTalkRoomServiceClient(m.cli.Conn())
	return client.SendGift(ctx, in, opts...)
}

func (m *defaultTalkRoomService) StartRaffle(ctx context.Context, in *StartRaffleReq, opts ...grpc.CallOption) (*StartRaffleResp, error) {
	client := pb.NewTalkRoomServiceClient(m.cli.Conn())
	return client.StartRaffle(ctx, in, opts...)
}

func (m *defaultTalkRoomService) JoinRaffle(ctx context.Context, in *JoinRaffleReq, opts ...grpc.CallOption) (*JoinRaffleResp, error) {
	client := pb.NewTalkRoomServiceClient(m.cli.Conn())
	return client.JoinRaffle(ctx, in, opts...)
}
