// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"mygo/app/chatCenter/chat-rpc/internal/logic"
	"mygo/app/chatCenter/chat-rpc/internal/svc"
	"mygo/app/chatCenter/chat-rpc/pb/pb"
)

type ChatRoomServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatRoomServiceServer
}

func NewChatRoomServiceServer(svcCtx *svc.ServiceContext) *ChatRoomServiceServer {
	return &ChatRoomServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatRoomServiceServer) CreatRoom(ctx context.Context, in *pb.CreatRoomReq) (*pb.CreatRoomResp, error) {
	l := logic.NewCreatRoomLogic(ctx, s.svcCtx)
	return l.CreatRoom(in)
}

func (s *ChatRoomServiceServer) SendGift(ctx context.Context, in *pb.SendGiftReq) (*pb.SendGiftResp, error) {
	l := logic.NewSendGiftLogic(ctx, s.svcCtx)
	return l.SendGift(in)
}

func (s *ChatRoomServiceServer) StartRaffle(ctx context.Context, in *pb.StartRaffleReq) (*pb.StartRaffleResp, error) {
	l := logic.NewStartRaffleLogic(ctx, s.svcCtx)
	return l.StartRaffle(in)
}

func (s *ChatRoomServiceServer) JoinRaffle(ctx context.Context, in *pb.JoinRaffleReq) (*pb.JoinRaffleResp, error) {
	l := logic.NewJoinRaffleLogic(ctx, s.svcCtx)
	return l.JoinRaffle(in)
}
