// Code generated by goctl. DO NOT EDIT.
// Source: room.proto

package server

import (
	"context"

	"mygo/app/roomCenter/room-rpc/internal/logic"
	"mygo/app/roomCenter/room-rpc/internal/svc"
	"mygo/app/roomCenter/room-rpc/pb/pb"
)

type RoomServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoomServiceServer
}

func NewRoomServiceServer(svcCtx *svc.ServiceContext) *RoomServiceServer {
	return &RoomServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RoomServiceServer) CreateRoom(ctx context.Context, in *pb.CreateRoomRequest) (*pb.CreateRoomResponse, error) {
	l := logic.NewCreateRoomLogic(ctx, s.svcCtx)
	return l.CreateRoom(in)
}

func (s *RoomServiceServer) JoinRoom(ctx context.Context, in *pb.JoinRoomRequest) (*pb.JoinRoomResponse, error) {
	l := logic.NewJoinRoomLogic(ctx, s.svcCtx)
	return l.JoinRoom(in)
}

func (s *RoomServiceServer) CloseRoom(ctx context.Context, in *pb.CloseRoomRequest) (*pb.CloseRoomResponse, error) {
	l := logic.NewCloseRoomLogic(ctx, s.svcCtx)
	return l.CloseRoom(in)
}

func (s *RoomServiceServer) GetRoom(ctx context.Context, in *pb.GetRoomRequest) (*pb.GetRoomResponse, error) {
	l := logic.NewGetRoomLogic(ctx, s.svcCtx)
	return l.GetRoom(in)
}

func (s *RoomServiceServer) GetOneRoomViewNum(ctx context.Context, in *pb.GetOneRoomViewNumRequest) (*pb.GetOneRoomViewNumResponse, error) {
	l := logic.NewGetOneRoomViewNumLogic(ctx, s.svcCtx)
	return l.GetOneRoomViewNum(in)
}
