// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"mygo/app/userCenter/user-rpc/internal/logic"
	"mygo/app/userCenter/user-rpc/internal/svc"
	"mygo/app/userCenter/user-rpc/pb/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) GetCode(ctx context.Context, in *pb.GetCodeReq) (*pb.GetCodeResp, error) {
	l := logic.NewGetCodeLogic(ctx, s.svcCtx)
	return l.GetCode(in)
}

func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServiceServer) Charge(ctx context.Context, in *pb.ChargeReq) (*pb.ChargeResp, error) {
	l := logic.NewChargeLogic(ctx, s.svcCtx)
	return l.Charge(in)
}

func (s *UserServiceServer) Spend(ctx context.Context, in *pb.SpendReq) (*pb.SpendResp, error) {
	l := logic.NewSpendLogic(ctx, s.svcCtx)
	return l.Spend(in)
}
