// Code generated by goctl. DO NOT EDIT.
// Source: model.proto

package server

import (
	"context"

	"mygo/app/talkCenter/talk-rpc/internal/logic"
	"mygo/app/talkCenter/talk-rpc/internal/svc"
	"mygo/app/talkCenter/talk-rpc/pb/pb"
)

type TalkRoomServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTalkRoomServiceServer
}

func NewTalkRoomServiceServer(svcCtx *svc.ServiceContext) *TalkRoomServiceServer {
	return &TalkRoomServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TalkRoomServiceServer) CreatRoom(ctx context.Context, in *pb.CreatRoomReq) (*pb.CreatRoomResp, error) {
	l := logic.NewCreatRoomLogic(ctx, s.svcCtx)
	return l.CreatRoom(in)
}

func (s *TalkRoomServiceServer) SendGift(ctx context.Context, in *pb.SendGiftReq) (*pb.SendGiftResp, error) {
	l := logic.NewSendGiftLogic(ctx, s.svcCtx)
	return l.SendGift(in)
}

func (s *TalkRoomServiceServer) StartRaffle(ctx context.Context, in *pb.StartRaffleReq) (*pb.StartRaffleResp, error) {
	l := logic.NewStartRaffleLogic(ctx, s.svcCtx)
	return l.StartRaffle(in)
}

func (s *TalkRoomServiceServer) JoinRaffle(ctx context.Context, in *pb.JoinRaffleReq) (*pb.JoinRaffleResp, error) {
	l := logic.NewJoinRaffleLogic(ctx, s.svcCtx)
	return l.JoinRaffle(in)
}
