// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "mygo/app/userCenter/user-api/internal/handler/user"
	"mygo/app/userCenter/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/charge",
				Handler: user.ChargeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/getUserInfo",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register/sendMessage",
				Handler: user.SendMessageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
