// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "mygo/app/chatCenter/chat-api/internal/handler/chat"
	"mygo/app/chatCenter/chat-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:room",
				Handler: chat.ServeHomeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gift",
				Handler: chat.GiftHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/joinRaffle",
				Handler: chat.JoinRaffleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/startRaffle",
				Handler: chat.StartRaffleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws/:room",
				Handler: chat.TalkWSHandler(serverCtx),
			},
		},
	)
}
