// Code generated by goctl. DO NOT EDIT.
// Source: room.proto

package roomservice

import (
	"context"

	"mygo/app/roomCenter/room-rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CloseRoomRequest   = pb.CloseRoomRequest
	CloseRoomResponse  = pb.CloseRoomResponse
	CreateRoomRequest  = pb.CreateRoomRequest
	CreateRoomResponse = pb.CreateRoomResponse
	GetOneRoomRequest  = pb.GetOneRoomRequest
	GetOneRoomResponse = pb.GetOneRoomResponse
	GetRoomRequest     = pb.GetRoomRequest
	GetRoomResponse    = pb.GetRoomResponse
	JoinRoomRequest    = pb.JoinRoomRequest
	JoinRoomResponse   = pb.JoinRoomResponse
	Room               = pb.Room

	RoomService interface {
		CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
		JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
		CloseRoom(ctx context.Context, in *CloseRoomRequest, opts ...grpc.CallOption) (*CloseRoomResponse, error)
		GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error)
		GetOneRoom(ctx context.Context, in *GetOneRoomRequest, opts ...grpc.CallOption) (*GetOneRoomResponse, error)
	}

	defaultRoomService struct {
		cli zrpc.Client
	}
)

func NewRoomService(cli zrpc.Client) RoomService {
	return &defaultRoomService{
		cli: cli,
	}
}

func (m *defaultRoomService) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	client := pb.NewRoomServiceClient(m.cli.Conn())
	return client.CreateRoom(ctx, in, opts...)
}

func (m *defaultRoomService) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	client := pb.NewRoomServiceClient(m.cli.Conn())
	return client.JoinRoom(ctx, in, opts...)
}

func (m *defaultRoomService) CloseRoom(ctx context.Context, in *CloseRoomRequest, opts ...grpc.CallOption) (*CloseRoomResponse, error) {
	client := pb.NewRoomServiceClient(m.cli.Conn())
	return client.CloseRoom(ctx, in, opts...)
}

func (m *defaultRoomService) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*GetRoomResponse, error) {
	client := pb.NewRoomServiceClient(m.cli.Conn())
	return client.GetRoom(ctx, in, opts...)
}

func (m *defaultRoomService) GetOneRoom(ctx context.Context, in *GetOneRoomRequest, opts ...grpc.CallOption) (*GetOneRoomResponse, error) {
	client := pb.NewRoomServiceClient(m.cli.Conn())
	return client.GetOneRoom(ctx, in, opts...)
}
